# config/packages/security.yaml

security:
    # Configuration pour le hashage des mots de passe
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    
    # Configuration pour les fournisseurs d'utilisateurs
    providers:
        users_in_memory: { memory: null }
    
    # Configuration des firewalls
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: users_in_memory
            
            # Configuration de form_login
            form_login:
                login_path: app_login
                check_path: app_login
                default_target_path: home # Rediriger vers la page d'accueil après la connexion
                username_parameter: 'email' # Utiliser le nom complet du champ
                password_parameter: 'password' # Utiliser le nom complet du champ

            # Autres configurations possibles
            # https://symfony.com/doc/current/security.html#the-firewall
            # switch_user: true

    # Contrôle d'accès
    access_control:
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }

# Configuration de sécurité pour l'environnement de test
when@test:
    security:
        password_hashers:
            App\Entity\Camping: 'auto'
