security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    
    providers:
        camping_provider:
            entity:
                class: App\Entity\Camping
                property: email
    
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: camping_provider

            # Ajoutez cette ligne pour spécifier le point d'entrée
            entry_point: App\Security\LoginFormAuthenticator

            form_login:
                login_path: app_login
                check_path: app_login
                default_target_path: home
                username_parameter: 'email'
                password_parameter: 'password'

            custom_authenticator: App\Security\LoginFormAuthenticator

            logout:
                path: app_logout
                target: app_login

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/profile, roles: ROLE_USER }
